name: Label Checker

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

jobs:
  check_labels:
    name: Check labels
    runs-on: ubuntu-latest
    steps:
      - uses: docker://agilepathway/pull-request-label-checker:v1.6.13
        with:
          one_of: norelease,release:major,release:minor,release:patch
          repo_token: ${{ secrets.GITHUB_TOKEN }}