name: Release on Push

on:
  push:
    branches:
      - main
      - v1.X

jobs:
  release_on_push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: rymndhng/release-on-push-action@aebba2bbce07a9474bf95e8710e5ee8a9e922fe2 # v0.28.0
        with:
          bump_version_scheme: norelease
          use_github_release_notes: true
