name: Test

on:
  push:
    branches:
      - main
      - v1.X
  pull_request:
    branches:
      - main
      - v1.X

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  run-test:
    name: Run test
    runs-on: ubuntu-latest

    permissions:
      actions: write

    steps:
      - name: Check out git repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: "yarn"

      - name: Install yarn dependencies
        run: yarn install

      - name: Test
        run: yarn test